from tkinter import *
from tkinter import messagebox as mb
from tkinter import ttk

root = Tk()
def getresult():
        #LOGIC
    float(cmb1.get())
    str(cmb2.get())
    if (float(cmb1.get())>=38 and float(cmb1.get())<=40 and str(cmb2.get())=="Yes" and str(cmb3.get())=="Middle" and str(cmb4.get())=="No" and str(cmb5.get())=="Middle" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="All over the body"):
            mb.showinfo(title='Diagnosis', message='Measles')
    elif (float(cmb1.get())>=38 and float(cmb1.get())<=40 and str(cmb2.get())=="Yes" and str(cmb3.get())=="No" and str(cmb4.get())=="No" and str(cmb5.get())=="No" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="Local"):
            mb.showinfo(title='Diagnosis', message='Scarlet fever')
    elif (float(cmb1.get())>=37 and float(cmb1.get())<=41 and str(cmb2.get())=="Yes" and str(cmb3.get())=="Strong" and str(cmb4.get())=="No" and str(cmb5.get())=="Strong" and str(cmb6.get())=="No" and str(cmb7.get())=="Middle" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="No"):
            mb.showinfo(title='Diagnosis', message='Influenza')
    elif (float(cmb1.get())>=37 and float(cmb1.get())<=38 and str(cmb2.get())=="Yes" and str(cmb3.get())=="Easy" and str(cmb4.get())=="Yes" and str(cmb5.get())=="Easy" and str(cmb6.get())=="Yes" and str(cmb7.get())=="Easy" and str(cmb8.get())=="Easy" and str(cmb9.get())=="Easy" and str(cmb10.get())=="Easy" and str(cmb11.get())=="No"):
            mb.showinfo(title='Diagnosis', message='VRI')
    elif (float(cmb1.get())>=38 and float(cmb1.get())<=40 and str(cmb2.get())=="Yes" and str(cmb3.get())=="No" and str(cmb4.get())=="No" and str(cmb5.get())=="No" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="All over the body"):
            mb.showinfo(title='Diagnosis', message='Chickenpox')
    elif (float(cmb1.get())>=38 and float(cmb1.get())<=40 and str(cmb2.get())=="Yes" and str(cmb3.get())=="No" and str(cmb4.get())=="No" and str(cmb5.get())=="No" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="No"):
            mb.showinfo(title='Diagnosis', message='Meningitis')
    elif (float(cmb1.get())>=38 and float(cmb1.get())<=40 and str(cmb2.get())=="Yes" and str(cmb3.get())=="No" and str(cmb4.get())=="No" and str(cmb5.get())=="No" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Middle" and str(cmb10.get())=="Middle" and str(cmb11.get())=="No"):
            mb.showinfo(title='Diagnosis', message='Mumps')
    elif (float(cmb1.get())>=38 and float(cmb1.get())<=40 and str(cmb2.get())=="Yes" and str(cmb3.get())=="No" and str(cmb4.get())=="No" and str(cmb5.get())=="Strong" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="No"):
            mb.showinfo(title='Diagnosis', message='Tonsillitis')
    elif (float(cmb1.get())>=38 and float(cmb1.get())<=42 and str(cmb2.get())=="Yes" and str(cmb3.get())=="No" and str(cmb4.get())=="No" and str(cmb5.get())=="Strong" and str(cmb6.get())=="No" and str(cmb7.get())=="Strong" and str(cmb8.get())=="Strong" and str(cmb9.get())=="Strong" and str(cmb10.get())=="Strong" and str(cmb11.get())=="No"):
            mb.showinfo(title='Diagnosis', message='Diphtheria')
    else:
            mb.showinfo(title='Diagnosis', message='Error')

#GUI
def show_info():
    mb.showinfo(title='Info', message='Only viral and bacterial diseases can be diagnosed')

root['bg']='#000000'
root.title('Medical diagnostics')
root.wm_attributes('-alpha', 1)
root.geometry('650x335')
root.resizable(width=False, height=False)
canvas=Canvas(root, height=300, width=700)
canvas.pack()
frame=Frame(root, bg='black')
frame.place(relwidth=1, relheight=1)
title=Label(frame, text='Medical diagnostics', bg='white', font=("Times New Roman", 17, "bold"))
title.pack()
title1=Label(frame, text='Temperature', bg='white', font=("Times New Roman", 17, "bold"))
title1.pack()
title1.place(x=12, y=80)
title2=Label(frame, text='Chills', bg='white', font=("Times New Roman", 17, "bold"))
title2.pack()
title2.place(x=215, y=80)
title3=Label(frame, text='Cough', bg='white', font=("Times New Roman", 17, "bold"))
title3.pack()
title3.place(x=370, y=80)
title4=Label(frame, text='Runny nose', bg='white', font=("Times New Roman", 17, "bold"))
title4.pack()
title4.place(x=506, y=80)
title5=Label(frame, text='Sore throat', bg='white', font=("Times New Roman", 17, "bold"))
title5.pack()
title5.place(x=20, y=147)
title6=Label(frame, text='Sneezing', bg='white', font=("Times New Roman", 17, "bold"))
title6.pack()
title6.place(x=197, y=147)
title7=Label(frame, text='Pain in head', bg='white', font=("Times New Roman", 17, "bold"))
title7.pack()
title7.place(x=341, y=147)
title8=Label(frame, text='Pain in muscles', bg='white', font=("Times New Roman", 17, "bold"))
title8.pack()
title8.place(x=490, y=147)
title9=Label(frame, text='Body aches', bg='white', font=("Times New Roman", 17, "bold"))
title9.pack()
title9.place(x=102, y=214)
title10=Label(frame, text='General malaise', bg='white', font=("Times New Roman", 17, "bold"))
title10.pack()
title10.place(x=240, y=214)
title11=Label(frame, text='Rash', bg='white', font=("Times New Roman", 17, "bold"))
title11.pack()
title11.place(x=453, y=214)
cmb1= ttk.Combobox(root, values=[37, 37.5,37.8, 38,38.1,38.7,39,39.5,40,41,42], font=("Times New Roman", 8, "bold"))
cmb1.pack()
cmb1.place(x=10, y=119)
cmb2= ttk.Combobox(root, values=["Yes","No"], font=("Times New Roman", 8, "bold"))
cmb2.pack()
cmb2.place(x=172, y=119)
cmb3= ttk.Combobox(root, values=["No", "Easy", "Middle", "Strong"], font=("Times New Roman", 8, "bold"))
cmb3.pack()
cmb3.place(x=334, y=119)
cmb4= ttk.Combobox(root, values=["Yes","No"], font=("Times New Roman", 8, "bold"))
cmb4.pack()
cmb4.place(x=496, y=119)
cmb5= ttk.Combobox(root, values=["No", "Easy", "Middle", "Strong"], font=("Times New Roman", 8, "bold"))
cmb5.pack()
cmb5.place(x=10, y=186)
cmb6= ttk.Combobox(root, values=["Yes","No"], font=("Times New Roman", 8, "bold"))
cmb6.pack()
cmb6.place(x=172, y=186)
cmb7= ttk.Combobox(root, values=["No", "Easy", "Middle", "Strong"], font=("Times New Roman", 8, "bold"))
cmb7.pack()
cmb7.place(x=334, y=186)
cmb8= ttk.Combobox(root, values=["No", "Easy", "Middle", "Strong"], font=("Times New Roman", 8, "bold"))
cmb8.pack()
cmb8.place(x=496, y=186)
cmb9= ttk.Combobox(root, values=["No", "Easy", "Middle", "Strong"], font=("Times New Roman", 8, "bold"))
cmb9.pack()
cmb9.place(x=90, y=253)
cmb10= ttk.Combobox(root, values=["No", "Easy", "Middle", "Strong"], font=("Times New Roman", 8, "bold"))
cmb10.pack()
cmb10.place(x=250, y=253)
cmb11= ttk.Combobox(root, values=["No", "Local", "All over the body"], font=("Times New Roman", 8, "bold"))
cmb11.pack()
cmb11.place(x=410, y=253)
btn=Button(frame, text='Get diagnosis', bg='green', command=getresult, font=("Times New Roman", 12, "bold"))
btn.pack()
btn.place(x=285, y=285)
btn1=Button(frame, text='Info', bg='red', command=show_info, font=("Times New Roman", 12, "bold"))
btn1.pack()
btn1.place(x=600, y=10)
root.mainloop()